### ISSUE TITLE
hunter-timing crush on process start

### ISSUE THREAD

**Issue by zhengzhou** [Leaking/Hunter#11]
```
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.hunter.library.timing.IBlockHandler.timingMethod(java.lang.String, int)' on a null object reference
        at com.hunter.library.timing.BlockManager.timingMethod(BlockManager.java:18)
        at com.hunter.library.timing.IBlockHandler.<clinit>(IBlockHandler.java:10)
        at com.hunter.library.timing.BlockManager.<clinit>(BlockManager.java:10) 
        at com.hunter.library.timing.BlockManager.timingMethod(Unknown Source:0) 
        at com.android.camera.CameraApp.<init>(CameraApp.java:34) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1063) 
```
看着是在自己初始化也插入了打日志的代码, 是不是默认吧自身给排除掉好一点.

**Comment by zhengzhou** [comment]
刚刚看了代码确实是排除了, 但是我这边确实在启动的时候就挂, 用白名单可以启动, 但是不是匹配字符串开头的, 和`com/quinn/hunter/plugin/timing/bytecode/TimingWeaver.java`的逻辑也不同, 是我的版本有问题吗, 

```
classpath 'com.quinn.hunter:hunter-timing-plugin:0.9.1'
classpath 'com.quinn.hunter:hunter-transform:0.9.2'
```

```
implementation 'com.quinn.hunter:hunter-timing-library:0.9.1'
```

**Comment by Leaking** [comment]
能否弄一个能复现这个问题的小项目，然后传到github，我去看看

**Comment by Leaking** [comment]
看起来是timingMethod方法中iBlockHandler变成空指针了，你是不是把它置空了？
```java
public class BlockManager {

    private static IBlockHandler iBlockHandler = IBlockHandler.DEFAULT;

    public static void installBlockManager(IBlockHandler custom) {
        BlockManager.iBlockHandler = custom;
    }

    public static void timingMethod(String method, long cost) {
        if (Looper.myLooper() == Looper.getMainLooper()) {
            iBlockHandler.timingMethod(method, (int)cost);
        }
    }

}
```

**Comment by zhengzhou** [comment]
不是的, 我是按文档加的依赖, 没有配置java的代码,也没有其他额外修改.

 似乎是在`IBlockHandler.DEFAULT`的构造函数里面又调用了`timingMethod`方法, 还没构造好所有是NPE, 我这边是java8的多Module的项目,  公司环境不太方便传项目上去.  问题还没查出来, 我今天再找一下

**Comment by Leaking** [comment]
你是用mac还是windows

**Comment by zhengzhou** [comment]
windows

**Comment by Leaking** [comment]
嗯，我今晚下班找个window机器排查下问题。

**Comment by Leaking** [comment]
@zhengzhou  fix了
将
```groovy
classpath 'com.quinn.hunter:hunter-transform:0.9.2'
```
升级为
```groovy
classpath 'com.quinn.hunter:hunter-transform:0.9.3'
```
即可。


大致原因是，错误处理了jar包中entryname的分隔符。
可以在你那边验证下，有问题欢迎继续反馈
