### ISSUE TITLE
报一个编译错误-NPE

### ISSUE THREAD

**Issue by pk00789o** [Leaking/Hunter#19]
Caused by: java.lang.NullPointerException
	at java.lang.String.<init>(String.java:204)
	at org.objectweb.asm.Type.getInternalName(Type.java:589)
	at org.objectweb.asm.commons.LocalVariablesSorter.newLocal(LocalVariablesSorter.java:286)
	at com.quinn.hunter.plugin.debug.bytecode.DebugMethodAdapter.visitInsn(DebugMethodAdapter.java:103)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1466)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.quinn.hunter.plugin.debug.bytecode.DebugWeaver.weaveSingleClassToByteArray(DebugWeaver.java:36)
	at com.quinn.hunter.transform.asm.BaseWeaver.weaveJar(BaseWeaver.java:53)
	at com.quinn.hunter.transform.HunterTransform.lambda$transformJar$2(HunterTransform.java:212)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by Leaking** [comment]
能否定位到具体是哪个class出错，或者提供一个最小可复现问题的repo链接

**Comment by stfnt** [comment]
hello，我正想提这个issues，当我在测试一些方法时候，发现会抛出一个NullPointerException

**Comment by stfnt** [comment]
这是我测试的方法：
@HunterDebug
    private void test2(){
        throw new RuntimeException("not impl");
    }

**Comment by stfnt** [comment]
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/37100963/60756637-481a4180-a032-11e9-8a1e-906d557d5417.png">

**Comment by stfnt** [comment]
发现是Void类型不允许新建变量，已经修复
https://github.com/Leaking/Hunter/pull/21

**Comment by Leaking** [comment]
@stfnt  已帮忙fix这个BUG了
这个BUG在hunter-debug插件存在，已更新版本，可以查看[readme](https://github.com/Leaking/Hunter/blob/master/README_hunter_debug.md)文档更新依赖，plugin和library需要一起更新到0.9.6
