### ISSUE TITLE
UnsupportedOperationException: java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by TangHuaiZhe** [Leaking/Hunter#32]
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task 
。。。。。
**Caused by: java.lang.UnsupportedOperationException ,This feature requires ASM6
        at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:135)
        at org.objectweb.asm.ClassReader.readModule(ClassReader.java:715)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:536)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at com.quinn.hunter.transform.asm.BaseWeaver.weaveSingleClassToByteArray(BaseWeaver.java:99)
        at com.quinn.hunter.transform.asm.BaseWeaver.weaveJar(BaseWeaver.java:53)
        at com.quinn.hunter.transform.HunterTransform.lambda$transformJar$2(HunterTransform.java:212)**

**Comment by TangHuaiZhe** [comment]
编译错误，clean多次仍然不行

**Comment by androidfu** [comment]
Can you please merge this?  :)

**Comment by FrozenFreeFall** [comment]
+1

**Comment by Leaking** [comment]
latest version has fixed this bug
