### ISSUE TITLE
When I weave jar, I got an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by bgylde** [Leaking/Hunter#5]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4  
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.quinn.hunter.transform.asm.BaseWeaver.weaveSingleClassToByteArray(BaseWeaver.java:95)
	at com.quinn.hunter.transform.asm.BaseWeaver.weaveJar(BaseWeaver.java:49)
	at com.quinn.hunter.transform.HunterTransform.transformJar(HunterTransform.java:213)
	at com.quinn.hunter.transform.HunterTransform.transform(HunterTransform.java:128)
	at com.quinn.hunter.plugin.okhttp.OkHttpHunterTransform.transform(OkHttpHunterTransform.java:35)
	at com.android.build.api.transform.Transform.transform(Transform.java:288)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:222)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:218)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:213)`

**Comment by Leaking** [comment]
what's your version of okhttp

**Comment by bgylde** [comment]
It's error in my jar, just close it.
